# Exploratory Data Analysis

Goal: fraud rate, fraud by type, amounts over time

In [3]:
import pandas as pd

In [8]:
df= pd.read_csv("../data/raw/paysim.csv")

In [9]:
df.shape

(6362620, 11)

In [19]:
df.head(10)

,step,type,amount,nameorig,oldbalanceorg,newbalanceorig,namedest,oldbalancedest,newbalancedest,isfraud,isflaggedfraud
0,1,PAYMENT,9839.64,C1231006815,170136.00,160296.36,M1979787155,0.0,0.00,0,0
1,1,PAYMENT,1864.28,C1666544295,21249.00,19384.72,M2044282225,0.0,0.00,0,0
2,1,TRANSFER,181.00,C1305486145,181.00,0.00,C553264065,0.0,0.00,1,0
3,1,CASH_OUT,181.00,C840083671,181.00,0.00,C38997010,21182.0,0.00,1,0
4,1,PAYMENT,11668.14,C2048537720,41554.00,29885.86,M1230701703,0.0,0.00,0,0
5,1,PAYMENT,7817.71,C90045638,53860.00,46042.29,M573487274,0.0,0.00,0,0
6,1,PAYMENT,7107.77,C154988899,183195.00,176087.23,M408069119,0.0,0.00,0,0
7,1,PAYMENT,7861.64,C1912850431,176087.23,168225.59,M633326333,0.0,0.00,0,0
8,1,PAYMENT,4024.36,C1265012928,2671.00,0.00,M1176932104,0.0,0.00,0,0
9,1,DEBIT,5337.77,C712410124,41720.00,36382.23,C195600860,41898.0,40348.79,0,0

In [18]:
df.info()
df.columns=df.columns.str.lower()

<class 'pandas.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 11 columns):
 #   Column          Dtype
---  ------          -----
 0   step            int64
 1   type            str
 2   amount          float64
 3   nameOrig        str
 4   oldbalanceOrg   float64
 5   newbalanceOrig  float64
 6   nameDest        str
 7   oldbalanceDest  float64
 8   newbalanceDest  float64
 9   isFraud         int64
 10  isFlaggedFraud  int64
dtypes: float64(5), int64(3), str(3)
memory usage: 706.2 MB

In [34]:
fraud_checker= df[(df["isfraud"]==1) & (df["type"]=='TRANSFER')]
fraud_checker[fraud_checker["namedest"].isin(df["nameorig"])]

,step,type,amount,nameorig,oldbalanceorg,newbalanceorig,namedest,oldbalancedest,newbalancedest,isfraud,isflaggedfraud
1030443,65,TRANSFER,1282971.57,C1175896731,1282971.57,0.0,C1714931087,0.0,0.0,1,0
3948136,287,TRANSFER,491847.47,C1042812790,491847.47,0.0,C610496257,0.0,0.0,1,0
4240012,306,TRANSFER,4262592.28,C261172273,4262592.28,0.0,C1673497915,0.0,0.0,1,0
6009966,442,TRANSFER,355969.72,C227175045,355969.72,0.0,C765607741,0.0,0.0,1,0
6020276,461,TRANSFER,830991.53,C1642150548,830991.53,0.0,C1757788418,0.0,0.0,1,0
6020336,463,TRANSFER,1968008.53,C1548769886,1968008.53,0.0,C1779956771,0.0,0.0,1,0
6039814,486,TRANSFER,214793.32,C2140495649,214793.32,0.0,C423543548,0.0,0.0,1,0
6362556,738,TRANSFER,814689.88,C2029041842,814689.88,0.0,C1023330867,0.0,0.0,1,0