# Exploratory Data Analysis

Goal: fraud rate, fraud by type, amounts over time

In [1]:
import pandas as pd

In [2]:
df= pd.read_csv("../data/raw/paysim.csv")

In [3]:
df.shape

(6362620, 11)

In [4]:
df.head(10)

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.00,160296.36,M1979787155,0.0,0.00,0,0
1,1,PAYMENT,1864.28,C1666544295,21249.00,19384.72,M2044282225,0.0,0.00,0,0
2,1,TRANSFER,181.00,C1305486145,181.00,0.00,C553264065,0.0,0.00,1,0
3,1,CASH_OUT,181.00,C840083671,181.00,0.00,C38997010,21182.0,0.00,1,0
4,1,PAYMENT,11668.14,C2048537720,41554.00,29885.86,M1230701703,0.0,0.00,0,0
5,1,PAYMENT,7817.71,C90045638,53860.00,46042.29,M573487274,0.0,0.00,0,0
6,1,PAYMENT,7107.77,C154988899,183195.00,176087.23,M408069119,0.0,0.00,0,0
7,1,PAYMENT,7861.64,C1912850431,176087.23,168225.59,M633326333,0.0,0.00,0,0
8,1,PAYMENT,4024.36,C1265012928,2671.00,0.00,M1176932104,0.0,0.00,0,0
9,1,DEBIT,5337.77,C712410124,41720.00,36382.23,C195600860,41898.0,40348.79,0,0

In [5]:
df.info()
df.columns=df.columns.str.lower()

<class 'pandas.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 11 columns):
 #   Column          Dtype
---  ------          -----
 0   step            int64
 1   type            str
 2   amount          float64
 3   nameOrig        str
 4   oldbalanceOrg   float64
 5   newbalanceOrig  float64
 6   nameDest        str
 7   oldbalanceDest  float64
 8   newbalanceDest  float64
 9   isFraud         int64
 10  isFlaggedFraud  int64
dtypes: float64(5), int64(3), str(3)
memory usage: 706.2 MB

In [8]:
fraud_checker= df[(df["isfraud"]==1) & (df["type"]=='TRANSFER')]
fraud_checker[fraud_checker["namedest"].isin(df["nameorig"])]

,step,type,amount,nameorig,oldbalanceorg,newbalanceorig,namedest,oldbalancedest,newbalancedest,isfraud,isflaggedfraud
1030443,65,TRANSFER,1282971.57,C1175896731,1282971.57,0.0,C1714931087,0.0,0.0,1,0
3948136,287,TRANSFER,491847.47,C1042812790,491847.47,0.0,C610496257,0.0,0.0,1,0
4240012,306,TRANSFER,4262592.28,C261172273,4262592.28,0.0,C1673497915,0.0,0.0,1,0
6009966,442,TRANSFER,355969.72,C227175045,355969.72,0.0,C765607741,0.0,0.0,1,0
6020276,461,TRANSFER,830991.53,C1642150548,830991.53,0.0,C1757788418,0.0,0.0,1,0
6020336,463,TRANSFER,1968008.53,C1548769886,1968008.53,0.0,C1779956771,0.0,0.0,1,0
6039814,486,TRANSFER,214793.32,C2140495649,214793.32,0.0,C423543548,0.0,0.0,1,0
6362556,738,TRANSFER,814689.88,C2029041842,814689.88,0.0,C1023330867,0.0,0.0,1,0

In [9]:
len(fraud_checker)

4097

hmm tracking the money wont work here its too less data

In [10]:
receivers = fraud_checker[fraud_checker["namedest"].isin(df["nameorig"])]["namedest"]
df[df["nameorig"].isin(receivers)]

,step,type,amount,nameorig,oldbalanceorg,newbalanceorig,namedest,oldbalancedest,newbalancedest,isfraud,isflaggedfraud
1168398,132,CASH_OUT,29084.28,C1023330867,51999.00,22914.72,C1422447255,0.00,29084.28,0,0
1673806,158,TRANSFER,365864.65,C765607741,0.00,0.00,C148606101,2219927.59,2585792.24,0,0
2186261,185,CASH_OUT,214555.85,C423543548,0.00,0.00,C1066927674,4575179.83,4789735.69,0,0
2873970,227,CASH_IN,125386.20,C1779956771,7200064.13,7325450.33,C51972262,3216793.00,3091406.80,0,0
2921898,229,PAYMENT,8331.83,C610496257,0.00,0.00,M1667947127,0.00,0.00,0,0
3536868,259,CASH_IN,136278.81,C1757788418,249308.00,385586.81,C1411030515,166970.63,30691.82,0,0
3689826,277,PAYMENT,2266.88,C1673497915,0.00,0.00,M206834067,0.00,0.00,0,0
6149940,546,CASH_OUT,18091.05,C1714931087,197227.00,179135.95,C1339132632,66177.84,84268.89,0,0

In [11]:
fraud_df=df[df["isfraud"]==1]
normal_df=df[df["isfraud"]==0]

In [12]:
len(df)==len(fraud_df)+len(normal_df)

True

In [13]:
(fraud_df["oldbalancedest"]==fraud_df["newbalancedest"]).mean()

np.float64(0.4975039571411177)

In [14]:
(normal_df["oldbalancedest"]==normal_df["newbalancedest"]).mean()

np.float64(0.36403176567065976)

In [15]:
fraud_df["type"].value_counts()

type
CASH_OUT    4116
TRANSFER    4097
Name: count, dtype: int64

In [7]:
merchant_rec=df[df["namedest"].str.startswith("M")]

In [16]:
merchant_rec.describe()

,step,amount,oldbalanceorg,newbalanceorig,oldbalancedest,newbalancedest,isfraud,isflaggedfraud
count,2.151495e+06,2.151495e+06,2.151495e+06,2.151495e+06,2151495.0,2151495.0,2151495.0,2151495.0
mean,2.443782e+02,1.305760e+04,6.821683e+04,6.183789e+04,0.0,0.0,0.0,0.0
std,1.426951e+02,1.255645e+04,1.989911e+05,1.969915e+05,0.0,0.0,0.0,0.0
min,1.000000e+00,2.000000e-02,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0
25%,1.560000e+02,4.383820e+03,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0
50%,2.490000e+02,9.482190e+03,1.053000e+04,0.000000e+00,0.0,0.0,0.0,0.0
75%,3.350000e+02,1.756122e+04,6.088300e+04,4.965413e+04,0.0,0.0,0.0,0.0
max,7.180000e+02,2.386380e+05,4.368662e+07,4.367380e+07,0.0,0.0,0.0,0.0

In [17]:
merchant_sen=df[df["nameorig"].str.startswith("M")]

In [19]:
len(merchant_sen)

0

In [22]:
new_normal=normal_df[normal_df["type"].isin(["CASH_OUT","TRANSFER"])]
(new_normal["oldbalancedest"]==new_normal["newbalancedest"]).mean()

np.float64(0.0006176245277308345)

wrong feature and all